using System;
using System.Collections;

using UnityEngine;

using TMPro;

public class UserInput : MonoBehaviour
{
    #region Singleton implementation
    
    public static UserInput Instance;
    private void Awake() => Instance = this;
    
    #endregion
    
    #region Events
    
    public event Action<string> OnSubmit;
    
    #endregion
    
    // These questions were generated by AI :)
    private readonly string[] defaultMessages = new string[]
    {
        "What is the highest mountain in the world?",
        "Which planet in our solar system has the most moons?",
        "Who painted the Mona Lisa?",
        "What is the capital of Peru?",
        "How many sides does a heptagon have?",
        "What is the boiling point of water at sea level?",
        "In which year did the first moon landing occur?",
        "Which element in the periodic table has the symbol Au?",
        "Who wrote 'Romeo and Juliet'?",
        "What is the tallest building in the world?",
        "How many legs does a spider have?",
        "What is the largest country by area?",
        "In which year did World War II end?",
        "Which gas do plants absorb from the atmosphere during photosynthesis?",
        "Who discovered penicillin?",
        "What is the capital of Australia?",
        "How many continents are there in the world?",
        "What is the chemical formula for water?",
        "In which year did the first smartphone (Nokia 3310) come out?",
        "Which planet has rings made mostly of ice and rock?",
        "Who invented the light bulb?",
        "How many colors are in the standard rainbow?",
        "What is the strongest natural material known to humans?",
        "In which year did the first Olympic Games take place?",
        "Which animal has the longest lifespan?"
    };

    private TMP_InputField _inputField;
    
    private bool IsAvailable;

    private void Start()
    {
        // Getting references
        _inputField = this.GetComponent<TMP_InputField>();
        
        // Adding submit event
        _inputField.onSubmit.AddListener(SubmitMessage);
    }
    
    private void Update()
    {
        // Checking for shift enter
        if (!Input.GetKey(KeyCode.LeftShift) && !Input.GetKey(KeyCode.RightShift)) return;
        if (!Input.GetKeyDown(KeyCode.Return) && !Input.GetKeyDown(KeyCode.KeypadEnter)) return;

        // Inserting a new line into the input field
        _inputField.text += "\n";
        _inputField.caretPosition = _inputField.text.Length;
        _inputField.ActivateInputField(); 
    }

    public void Activate()
    {
        // Activating submitting
        IsAvailable = true;
        
        // Focusing on input field
        _inputField.ActivateInputField();
    }

    private void SubmitMessage(string message)
    {
        // Checking for control
        if (Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift)) return;
        
        // Cheking for available
        if (!IsAvailable) return;
        IsAvailable = false;
        
        // Sending message
        message = message != string.Empty ? message : defaultMessages[UnityEngine.Random.Range(0, defaultMessages.Length)];
        Action<string> updateMessage = ConversationManager.Message(0);
        updateMessage.Invoke(message);
        
        // Invoking the event
        OnSubmit?.Invoke(message);
        
        // Clearing the input field
        StartCoroutine(WaitClear());
        IEnumerator WaitClear()
        {
            _inputField.DeactivateInputField();
            
            _inputField.textComponent.enabled = false;
            
            yield return new WaitForEndOfFrame();
            
            _inputField.textComponent.enabled = true;
            
            _inputField.text = string.Empty;
        }   
    }
    
    public static void ResetState() => Instance._inputField.text = string.Empty;
}
